const menuButton=document.querySelector('.menu-toggle');
const nav=document.querySelector('.main-nav');
if(menuButton&&nav){menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');}));}
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
const navLinks=[...document.querySelectorAll('.main-nav a[href^="#"]')];
const sections=navLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id));}});},{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(section=>observer.observe(section));}
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function loadReviews(){const grid=document.getElementById('reviews-grid');if(!grid)return;try{const r=await fetch('/api/reviews');const data=await r.json();if(!data.length){grid.innerHTML='';return;}grid.innerHTML=data.map(x=>`<article class="review-card"><div class="stars" aria-label="${x.stars} étoiles">${'★'.repeat(x.stars)}${'☆'.repeat(5-x.stars)}</div><strong>${esc(x.name)}</strong><p>${esc(x.comment)}</p></article>`).join('');}catch(e){grid.innerHTML='';}}
const reviewForm=document.getElementById('review-form');if(reviewForm){reviewForm.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('review-status');status.textContent='Envoi…';const fd=new FormData(reviewForm);const payload=Object.fromEntries(fd.entries());payload.stars=Number(payload.stars);try{const r=await fetch('/api/reviews',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error();reviewForm.reset();status.textContent='Merci. Votre témoignage est en attente de validation.';}catch{status.textContent='Envoi impossible pour le moment.';}});}
async function loadGallery(){const grid=document.getElementById('gallery-grid'),empty=document.getElementById('gallery-empty');if(!grid)return;try{const r=await fetch('/api/gallery');const data=await r.json();if(!data.length)return;empty.hidden=true;grid.innerHTML=data.map(x=>`<figure class="gallery-card"><img loading="lazy" src="/media/${encodeURIComponent(x.object_key)}" alt="${esc(x.title||'Action PC Rebond')}">${x.caption?`<figcaption>${esc(x.caption)}</figcaption>`:''}</figure>`).join('');}catch(e){}}
loadReviews();loadGallery();
