function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function clean(v,max){return String(v??'').trim().slice(0,max)}
export default {async fetch(req,env){const u=new URL(req.url),p=u.pathname;
try{
 if(p==='/api/reviews'&&req.method==='GET'){const {results}=await env.DB.prepare("SELECT id,name,stars,comment,created_at FROM testimonials WHERE status='published' ORDER BY created_at DESC LIMIT 60").all();return json(results)}
 if(p==='/api/reviews'&&req.method==='POST'){const b=await req.json();const name=clean(b.name,80),comment=clean(b.comment,1200),stars=Number(b.stars);if(!name||!comment||!Number.isInteger(stars)||stars<1||stars>5)return json({error:'Données invalides'},400);await env.DB.prepare("INSERT INTO testimonials(name,stars,comment,status,created_at) VALUES(?,?,?,'pending',datetime('now'))").bind(name,stars,comment).run();return json({ok:true},201)}
 if(p==='/api/gallery'&&req.method==='GET'){const {results}=await env.DB.prepare("SELECT id,object_key,title,caption,created_at FROM gallery ORDER BY created_at DESC LIMIT 100").all();return json(results)}
 if(p.startsWith('/media/')&&req.method==='GET'){const key=decodeURIComponent(p.slice(7));if(!key||key.includes('..'))return new Response('Not found',{status:404});const obj=await env.MEDIA.get(key);if(!obj)return new Response('Not found',{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set('etag',obj.httpEtag);h.set('cache-control','public,max-age=86400');return new Response(obj.body,{headers:h})}
 // IMPORTANT : toutes les routes /api/admin/* ET /admin.html doivent être protégées par Cloudflare Access.
 if(p==='/api/admin/reviews'&&req.method==='GET'){const {results}=await env.DB.prepare("SELECT * FROM testimonials WHERE status='pending' ORDER BY created_at ASC").all();return json(results)}
 let m=p.match(/^\/api\/admin\/reviews\/(\d+)\/publish$/);if(m&&req.method==='POST'){await env.DB.prepare("UPDATE testimonials SET status='published' WHERE id=?").bind(Number(m[1])).run();return json({ok:true})}
 m=p.match(/^\/api\/admin\/reviews\/(\d+)$/);if(m&&req.method==='DELETE'){await env.DB.prepare('DELETE FROM testimonials WHERE id=?').bind(Number(m[1])).run();return new Response(null,{status:204})}
 if(m&&req.method==='PUT'){const b=await req.json();await env.DB.prepare('UPDATE testimonials SET name=?,comment=? WHERE id=?').bind(clean(b.name,80),clean(b.comment,1200),Number(m[1])).run();return json({ok:true})}
 if(p==='/api/admin/gallery'&&req.method==='GET'){const {results}=await env.DB.prepare('SELECT * FROM gallery ORDER BY created_at DESC').all();return json(results)}
 if(p==='/api/admin/gallery'&&req.method==='POST'){const f=await req.formData(),file=f.get('photo');if(!(file instanceof File)||file.size===0||file.size>8*1024*1024)return json({error:'Photo invalide ou supérieure à 8 Mo'},400);if(!['image/jpeg','image/png','image/webp'].includes(file.type))return json({error:'Format non autorisé'},400);const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const key=`gallery/${Date.now()}-${crypto.randomUUID()}.${ext}`;await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type}});const r=await env.DB.prepare("INSERT INTO gallery(object_key,title,caption,created_at) VALUES(?,?,?,datetime('now')) RETURNING id").bind(key,clean(f.get('title'),120),clean(f.get('caption'),500)).first();return json({ok:true,id:r.id},201)}
 m=p.match(/^\/api\/admin\/gallery\/(\d+)$/);if(m&&req.method==='DELETE'){const row=await env.DB.prepare('SELECT object_key FROM gallery WHERE id=?').bind(Number(m[1])).first();if(row){await env.MEDIA.delete(row.object_key);await env.DB.prepare('DELETE FROM gallery WHERE id=?').bind(Number(m[1])).run();}return new Response(null,{status:204})}
 if(m&&req.method==='PUT'){const b=await req.json();await env.DB.prepare('UPDATE gallery SET title=?,caption=? WHERE id=?').bind(clean(b.title,120),clean(b.caption,500),Number(m[1])).run();return json({ok:true})}
 return env.ASSETS.fetch(req)
}catch(e){console.error(e);return json({error:'Erreur serveur'},500)}}}
